name: "build"
on: push
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        # We need a nix version with NixOS/nix#3564 to be able to use
        # `--max-jobs`, so using NixOS/nix@323e545. See 8365e73 for the problem
        # with `--max-jobs`. Install URL is obtained from CI logs for the nix
        # commit: https://github.com/NixOS/nix/runs/2895674848 expand "Run
        # cachenix/install-nix-action@v13" job, then the "Run
        # cachenix/install-nix-action@v13" step, and you'll see a line starting
        # with `install_url`.
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'

    # We are using the ic-hs-test cachix cache that is also used by
    # dfinity/ic-hs. This is partly laziness (on need to set up a separate
    # cache), but also to get the ic-ref-test binary without rebuilding
    - uses: cachix/cachix-action@v10
      with:
        name: ic-hs-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # until https://github.com/cachix/cachix-action/issues/86 is fixed:
    - run: cachix watch-store ic-hs-test &

    - name: "nix-build"
      run: nix-build --max-jobs 10 -A all-systems-go
